--solution #1

SELECT COUNT(*) FROM DEPARTMENTS;

--solution #2

SELECT COUNT(MANAGER_ID), COUNT(LOCATION_ID) FROM DEPARTMENTS;

--SOLUTION #3

SELECT COUNT(*) FROM DEPARTMENTS
WHERE DEPARTMENT_ID BETWEEN 10 AND 100
GROUP BY LOCATION_ID;
