--solution #1

SELECT a.*, b.JOB_TITLE, c.DEPARTMENT_NAME
  from EMPLOYEES a
LEFT OUTER JOIN JOBS b on a.JOB_ID = b.JOB_ID
LEFT OUTER JOIN DEPARTMENTS c on a.DEPARTMENT_ID = c.DEPARTMENT_ID;

--solution #2

SELECT a.*, b.JOB_TITLE, c.DEPARTMENT_NAME
  from EMPLOYEES a
LEFT OUTER JOIN JOBS b on a.JOB_ID = b.JOB_ID
LEFT OUTER JOIN DEPARTMENTS c on a.DEPARTMENT_ID = c.DEPARTMENT_ID
    where a.DEPARTMENT_ID BETWEEN 10 AND 40;

--solution #3

SELECT a.*, a.EMPLOYEE_ID, 
        a.FIRST_NAME, a.LAST_NAME, 
        a.JOB_ID, b.JOB_TITLE, 
        a.DEPARTMENT_ID, c.DEPARTMENT_NAME
from EMPLOYEES a
LEFT OUTER JOIN JOBS b on a.JOB_ID = b.JOB_ID
LEFT OUTER JOIN DEPARTMENTS c on a.DEPARTMENT_ID = c.DEPARTMENT_ID
    where a.DEPARTMENT_ID BETWEEN 10 AND 40;
