--solution #1

SELECT avg(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--solution #2

SELECT LAST_NAME, FIRST_NAME, sum(SALARY)
FROM EMPLOYEES
WHERE PHONE_NUMBER like '%1346%'
GROUP BY FIRST_NAME, LAST_NAME
ORDER BY LAST_NAME;

--solution #3

SELECT min(HIRE_DATE), max(HIRE_DATE) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

--solution #4

SELECT max(LAST_NAME) FROM EMPLOYEES;
