--solution #1

CREATE TABLE EM_EMPLOYEE_INFO(
    EMPLOYEE_ID   number,
    FIRST_NAME   varchar2(30),
    LAST_NAME   varchar2(30),
    PHONE_NUMBER   varchar2(30),
    HIRE_DATE   date);
    
    SELECT * FROM EM_EMPLOYEE_INFO;

--solution #2

INSERT INTO EM_EMPLOYEE_INFO(
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE)
VALUES(10, 'Gabriela', 'Hernandez', '111.222.333', '01.10.2019');
commit;

SELECT * FROM EM_EMPLOYEE_INFO;

--solution #3

INSERT INTO EM_EMPLOYEE_INFO(
EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE
    FROM HR.EMPLOYEES
WHERE PHONE_NUMBER LIKE '%5.123.4%';
    commit;

SELECT * FROM EM_EMPLOYEE_INFO;
