--solution #1

SELECT COUNT(DISTINCT CITY)
FROM LOCATIONS;

--solution #2

SELECT DISTINCT CITY, COUNTRY_ID
FROM LOCATIONS
ORDER BY CITY DESC;

--solution #3

SELECT DISTINCT COUNTRY_ID
FROM LOCATIONS
WHERE STATE_PROVINCE IS NOT NULL
ORDER BY COUNTRY_ID ASC;
