--solution #1

SELECT COUNTRY_ID, COUNT(STREET_ADDRESS)
FROM LOCATIONS
WHERE LOCATION_ID > 2000
GROUP BY COUNTRY_ID
HAVING COUNT(STREET_ADDRESS) >= 2;

--solution #2

SELECT STATE_PROVINCE
FROM LOCATIONS
ORDER BY STATE_PROVINCE ASC NULLS first;
